version: "3.5"

services:

  ftpd-server:
    image: stilliard/pure-ftpd
    container_name: ftp-server
    hostname: ftp-server
    volumes:
      - "/tmp/data-ftp:/home/username/"
      - "/tmp/passwd-ftp:/etc/pure-ftpd/passwd"
    environment:
      PUBLICHOST: "ftp-server"
      FTP_USER_NAME: ninetynine
      FTP_USER_PASS: ninetynine-rules
      FTP_USER_HOME: /home/username
    networks:
      - ninety_nine_net

  mongodb:
    image: mongo
    container_name: mongodb
    hostname: mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: ninetynine
      MONGO_INITDB_ROOT_PASSWORD: ninetyninerules
      MONGO_INITDB_DATABASE: nntransfers
    networks:
      - ninety_nine_net

  tansfer-uploader:
    image: jtejedor/ninety-nine:1.0.4-transferuploader
    container_name: tansfer-uploader
    depends_on:
      - ftpd-server
    links:
      - ftpd-server
    networks:
      - ninety_nine_net
    environment:
      FTPSERVER_HOSTNAME: ftpd-server
      FTPSERVER_USER: ninetynine
      FTPSERVER_PASSWORD: ninetynine-rules
      #Uncomment the line below for amount over 10 millions lines to increase heap memory and avoid OutOfMemory Exception
      #JAVA_OPTS: "-Xms4g -Xmx4g"
      FILE_TRANSFERAMOUNTLINES: 500
      #How many people are created with its iban and its nif
      #Each person has one nif and four iban (but due to a random process, the ibans might not be all fully used)
      TRANSFER_PEOPLE: 50
      #Used currencies to create random amounts
      #TRANSFER_CURRENCIES:
      # - USD
      # - EUR
      # - GBP
      # - CHF
      # - RUB
      # - DKK
      # - SEK
      #Maximum amount related to transfer
      TRANSFER_MAXAMOUNT: 1000
      #Probability that a part of transfer is malformed (1 - TRANSFER_PROBABILITYWRONG)
      #TRANSFER_PROBABILITYWRONG: 0.85
      #Global probability to create a full well fomatted transfer
      #TRANSFER_PROBABILITYGENERATION: 0.9
      #Probability that the amount field is in third position or last one
      #TRANSFER_PROBABILITYCHANGEAMOUNT: 0.5
  mongo-uploader:
    image: jtejedor/ninety-nine:1.0.2-mongouploader
    container_name: mongo-uploader
    depends_on:
      - ftpd-server
      - mongodb
    links:
      - ftpd-server
      - mongodb
    networks:
      - ninety_nine_net
    environment:
      FTPSERVER_HOSTNAME: ftpd-server
      FTPSERVER_USER: ninetynine
      FTPSERVER_PASSWORD: ninetynine-rules
      SPRING_DATA_MONGODB_URI: mongodb://ninetynine:ninetyninerules@mongodb:27017/nntransfers?authSource=admin

  transfer-backend:
    image: jtejedor/ninety-nine:1.0.1-transfer-backend
    container_name: transfer-backend
    hostname: transfer-backend
    depends_on:
      - mongodb
    links:
      - mongodb
    environment:
      SPRING_DATA_MONGODB_URI: mongodb://ninetynine:ninetyninerules@mongodb:27017/nntransfers?authSource=admin
    ports:
      - "8080:8080"
    networks:
      - ninety_nine_net

  frontend:
    image: jtejedor/ninetynine:1.0.0-frontend
    container_name: frontend
    depends_on:
      - transfer-backend
    links:
      - transfer-backend
    ports:
      - "4200:80"
    networks:
      - ninety_nine_net
networks:
    ninety_nine_net:
      name: ninety_nine_net
