version: '3'

services:
  ftpd_server:
    image: stilliard/pure-ftpd
    container_name: pure-ftpd
    ports:
      - "21:21"
      - "30000-30009:30000-30009"
    volumes:
      - "/tmp/data-ftp:/home/username/"
      - "/tmp/passwd-ftp:/etc/pure-ftpd/passwd"
    environment:
      PUBLICHOST: "localhost"
      FTP_USER_NAME: ninetynine
      FTP_USER_PASS: ninetynine-rules
      FTP_USER_HOME: /home/username
    restart: always
