spring:
  data:
    mongodb:
      uri: mongodb://ninetynine:ninetyninerules@localhost:27017/nntransfers?authSource=admin

logging:
  level:
    org.springframework.data.mongodb.core.MongoTemplate: TRACE
    org.springframework.data.mongodb.core.ReactiveMongoTemplate: TRACE